/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

extern uint8_t _heap_sdram_start;
extern uint8_t _heap_sdram_end;
extern void *__malloc_sbrk_base;

uint8_t *heap_ptr = NULL;

void* _sbrk(ptrdiff_t incr)
{
    if (heap_ptr == NULL)
    {
        heap_ptr = &_heap_sdram_start;
        __malloc_sbrk_base = &_heap_sdram_start;
    }

    uint8_t* prev_heap_ptr = heap_ptr;
    uint8_t* next_heap_ptr = heap_ptr + incr;

    if (next_heap_ptr > &_heap_sdram_end)
    {
        errno = ENOMEM;
        return (void*) -1;
    }

    heap_ptr = next_heap_ptr;
    return (void*) prev_heap_ptr;
}

void* _sbrk_r(struct _reent* r, ptrdiff_t incr)
{
    return _sbrk(incr);
}

